

dist:
  n_learners: 1
  n_workers: 3
  world_size: 4

hyp:
    n_epochs:  4
    n_agents:  8
    mini_batch_size:  4
    rollout_length:  16
    lr : 1e-4

rl:
  normalize_returns : true

paths:
  output_dir: "outputs/default"

model:
  actor_critic_share_weights: true
  encoder_conv_architecture: convnet_simple
  encoder_conv_mlp_layers : [512]
  encoder_mlp_layers : [512, 512]
  nonlinearity: "relu"
  
  use_rnn: false
  decoder_mlp_layers: []
  adaptive_stddev : true
  policy_init_gain : 1.0
  policy_initialization: orthogonal
  


obs:
  subtract_mean : 0.0
  scale : 1.0
  normalize_input : true
  normalize_input_keys : "*"
